name: "Compliance & Security Audit"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  terraform-audit:
    name: "Terraform Security Scan"
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform Nativo
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Code Syntax & Integrity Compliance Check
        run: |
          echo "==== Starting Structural Audit ===="
          terraform fmt -check || (echo "ERROR: Code structure or formatting does not comply with security standards" && exit 1)
          echo "==== SUCCESS: Structural Audit Passed (Zero Violations) ===="
        working-directory: ./infrastructure-as-code-azure
