name: "Compliance & Security Audit"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  terraform-audit:
    name: "Terraform Security Scan"
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/with/checkout@v3

      - name: Setup Terraform (Pinned Stable Version)
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.14.9" # Versión blindada libre de bugs de conexión
          terraform_wrapper: false

      - name: Terraform Init (Isolated Mode)
        run: terraform init -backend=false -input=false
        working-directory: ./infrastructure-as-code-azure

      - name: Security & Syntax Compliance Check
        run: terraform validate
        working-directory: ./infrastructure-as-code-azure
